### ISSUE TITLE
v0.2 release tracking

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/helm-chart#5]
- [x] Add support for global password to dummyauthenticator
- [x] Upgrade version of kubespawner
- [x] Better defaults for memory limits / cpu limits
- [x] Move culler into the hub pod

This is good I think

**Comment by yuvipanda** [comment]
Version has been released!
